format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  backend:                                             # name of the pipeline job that will be showing on UI
    group: App-Deployments
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/DevOps-58/ansible.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        SSH_PSW: "AES:n+ddBuplxzxe8DVndUpzGA==:w+Ky5mJPhdddBu68OJ1Wfg=="
        vault_token: "AES:9XlVsj95TTq/U7V7Q1D9mQ==:cJTw+TheeJY7vpbK6HV56EvuFUN7MmlinU4B4zx0GtM="
    environment_variables:
        COMPONENT: backend
    template: ansible-app-deployments