format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  frontend:                                             # name of the pipeline job that will be showing on UI
    group: App-Deployments
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/B58-CloudDevOps/ansible.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        SSH_PSW: "AES:Ek4CX8s3Rm1v66ck8o2lmA==:98jrieFLfuzj6cufTHWeNA=="
    environment_variables:
        COMPONENT: frontend
    template: App-Deployments-Template