format_version: 10
pipelines:
  mysql:
    group: App-Deployments
    label_template: "${COUNT}"
    materials:
      mysqlcode:
        git: https://github.com/DevOps-58/ansible.git
        branch: main
        auto-update: false
        shallow_clone: true
        display_order: -1
        lock_behaviour: none
    stages:
       - dev:                                        # Name of the stage 
           fetch_materials: true 
           keep_artifacts: false
           clean_workspace: false 
           jobs:
             Build:
               tasks:
                 - exec:
                     command: ls 
                     arguments:
                     - -ltr
       - qa:
           approval:
             type: manual
             allow_only_on_success: true
           jobs:
             Build:
               tasks:
                 - exec:
                     command: ls
                     arguments:
                     - -ltr
       - stage:
           approval:
             type: manual
             allow_only_on_success: true
           jobs:
             Build:
               tasks:
                 - exec:
                     command: ls 
                     arguments:
                     - -ltr

       - prod:
           fetch_materials: true 
           keep_artifacts: false
           clean_workspace: false 
           approval:
             type: manual
             allow_only_on_success: true
           jobs:
             Build:
               tasks:
                 - exec:
                     command: ls
                     arguments:
                     - -ltr