format_version: 10                
pipelines: 
  destroy:                                            
    group: Terraform
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/DevOps-58/expense-terraform.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        ssh_pwd: "AES:OojdR56nEjJZDswFYHyxRQ==:6PiGhXBgoVigGkmrT5MteQ=="
    environment_variables:
        COMPONENT: frontend
        action: destroy 
    stages:                                       
      - dev:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables: { env: dev }
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                - exec: { command: terraform, arguments: ["init", "backend.config", "env-dev/state.tfvars"] }
                - exec: { command: terraform, arguments: ["apply", "var-file", "env-dev/main.tfvars", "-auto-approve" ]}


      - prod:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables: { env: prod }
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                - exec: { command: terraform, arguments: ["init", "backend.config", "env-dev/state.tfvars"] }
                - exec: { command: terraform, arguments: ["apply", "var-file", "env-dev/main.tfvars", "-auto-approve" ]}