format_version: 10                
pipelines: 
  tools-infra-create:                                            
    group: Terraform
    label_template: "${COUNT}"
    materials:
      tools:
        git: https://github.com/DevOps-58/tools-automation.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        ssh_pwd: "AES:n+ddBuplxzxe8DVndUpzGA==:w+Ky5mJPhdddBu68OJ1Wfg=="
    environment_variables:
        action: apply 
    stages:                                       
      - infra:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          jobs:
            terraform:
              tasks:
                - exec: { command: bash, arguments: ["init.sh"] }
   