format_version: 10                
pipelines: 
  vault-cm:                                            
    group: Tools-CM
    label_template: "${COUNT}"
    materials:
      tools:
        git: https://github.com/DevOps-58/tools-automation.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        ssh_psw: "AES:OojdR56nEjJZDswFYHyxRQ==:6PiGhXBgoVigGkmrT5MteQ=="
    environment_variables:
        tool_name: vault 
    stages:                                       
      - infra:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          jobs:
            terraform:
              tasks:
                - exec: { command: bash, arguments: ["setup-tools.sh"] }
   